spring:
  application:
    name:melashor

  datasource:
    url:${SPRING_DATASOURCE_URL: jdbc://postgresql://localhost:5432/shopatease}
    username:${SPRING_DATASOURCE_USERNAME: melashor}
    password:${SPRING_DATASOURCE_PASSWORD: newpassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: updated




