services:
  db:
    image: postgre:latest
    ports:
      - "5342:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
      image: adminer:latest
      restart: always
      ports:
        - "8888:8080"

